# config/services.yaml

parameters:

services:
    # Configuration par défaut
    _defaults:
        autowire: true
        autoconfigure: true

    # Tous les services de /src sauf ceux exclus
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Extension Twig pour rendre "points" disponible partout
    App\Twig\PointsExtension:
        tags: ['twig.extension']
